### ISSUE TITLE
X86_X64路由器能跑吗？

### ISSUE THREAD

**Issue by RealKiro** [he0119/CoolQBot#27]
Lean的Openwrt恰好有Docker插件，是不是能抛弃服务器直接使用？配置过程能更简单点就好了不太好搞

**Comment by he0119** [comment]
应该有 Docker 的话就可以跑。配置过程的话，我不太会写文档🤣，你只要新建一个 `bot` 文件夹，放入 `bot.ini` 文件，然后在 `bot` 文件夹的上一级目录运行
```bash
sudo docker pull he0119/coolqbot:latest && \
sudo docker run -d --restart always --name coolqbot
  -v $(pwd)/coolq:/home/user/coolq \  # 将宿主目录挂载到容器内用于持久化酷 Q 的程序文件
  -v $(pwd)/bot:/home/user/coolqbot/bot \  # 将宿主目录挂载到容器内用于持久化机器人配置和数据文件
  -p 9000:9000 \  # noVNC 端口，用于从浏览器控制酷 Q
  -e COOLQ_ACCOUNT=2062765419 \ # 要登录的 QQ 账号，可选但建议填
  -e VNC_PASSWD=12345687 \ # noVNC 的密码（官方说不能超过 8 个字符，但实测可以超过）
  he0119/coolqbot:latest
```
这个命令就可以了。

bot.ini 的内容如下
```ini
[bot]
group_id = 438789224 # 你的群号
is_coolq_pro = 0 # 是否是 酷Q 专业版
admin = 417557420 # 管理员 QQ 号
nickname = 小誓约 小17 # 机器人昵称
tuling_api_key = # 图灵机器人的 APIKEY（没有就不用填）
tencent_ai_app_id = 
tencent_ai_app_key =  # 腾讯机器人的 APIKEY（没有就不用填）
```

**Comment by RealKiro** [comment]
> 应该有 Docker 的话就可以跑。配置过程的话，我不太会写文档🤣，你只要新建一个 `bot` 文件夹，放入 `bot.ini` 文件，然后在 `bot` 文件夹的上一级目录运行
> 
> ```shell
> sudo docker pull he0119/coolqbot:latest && \
> sudo docker run -d --restart always --name coolqbot
>   -v $(pwd)/coolq:/home/user/coolq \  # 将宿主目录挂载到容器内用于持久化酷 Q 的程序文件
>   -v $(pwd)/bot:/home/user/coolqbot/bot \  # 将宿主目录挂载到容器内用于持久化机器人配置和数据文件
>   -p 9000:9000 \  # noVNC 端口，用于从浏览器控制酷 Q
>   -e COOLQ_ACCOUNT=2062765419 \ # 要登录的 QQ 账号，可选但建议填
>   -e VNC_PASSWD=12345687 \ # noVNC 的密码（官方说不能超过 8 个字符，但实测可以超过）
>   he0119/coolqbot:latest
> ```
> 
> 这个命令就可以了。
> 
> bot.ini 的内容如下
> 
> ```ini
> [bot]
> group_id = 438789224 # 你的群号
> is_coolq_pro = 0 # 是否是 酷Q 专业版
> admin = 417557420 # 管理员 QQ 号
> nickname = 小誓约 小17 # 机器人昵称
> tuling_api_key = # 图灵机器人的 APIKEY（没有就不用填）
> tencent_ai_app_id = 
> tencent_ai_app_key =  # 腾讯机器人的 APIKEY（没有就不用填）
> ```
不行啊，我需要你的帮助
![image](https://user-images.githubusercontent.com/33367701/67399427-d2d17d00-f5de-11e9-9da3-3be3bc8a5696.png)

![image](https://user-images.githubusercontent.com/33367701/67399678-26dc6180-f5df-11e9-92b8-62e8a537c612.png)

难道要在路由终端运行？
![image](https://user-images.githubusercontent.com/33367701/67399817-5d19e100-f5df-11e9-911f-613c19314b9d.png)

**Comment by he0119** [comment]
嗯，那个命令是需要在路由器终端运行。但我没用过 `portainer.io` 不清楚这个该怎么用。

**Comment by he0119** [comment]
啊，我少加了一个 \ 符号。😂

你试试这段

```bash
sudo docker run -d --restart always --name coolqbot \
  -v $(pwd)/coolq:/home/user/coolq \  # 将宿主目录挂载到容器内用于持久化酷 Q 的程序文件
  -v $(pwd)/bot:/home/user/coolqbot/bot \  # 将宿主目录挂载到容器内用于持久化机器人配置和数据文件
  -p 9000:9000 \  # noVNC 端口，用于从浏览器控制酷 Q
  -e COOLQ_ACCOUNT=2062765419 \ # 要登录的 QQ 账号，可选但建议填
  -e VNC_PASSWD=12345687 \ # noVNC 的密码（官方说不能超过 8 个字符，但实测可以超过）
  he0119/coolqbot:latest
```

**Comment by RealKiro** [comment]
> ```shell
> sudo docker run -d --restart always --name coolqbot \
>   -v $(pwd)/coolq:/home/user/coolq \  # 将宿主目录挂载到容器内用于持久化酷 Q 的程序文件
>   -v $(pwd)/bot:/home/user/coolqbot/bot \  # 将宿主目录挂载到容器内用于持久化机器人配置和数据文件
>   -p 9000:9000 \  # noVNC 端口，用于从浏览器控制酷 Q
>   -e COOLQ_ACCOUNT=2062765419 \ # 要登录的 QQ 账号，可选但建议填
>   -e VNC_PASSWD=12345687 \ # noVNC 的密码（官方说不能超过 8 个字符，但实测可以超过）
>   he0119/coolqbot:latest
> ```

不行，我太难了
![image](https://user-images.githubusercontent.com/33367701/67401270-7facf980-f5e1-11e9-8d8a-dc87fdbbda91.png)

**Comment by he0119** [comment]
我的锅我的锅，你运行这个命令应该就没问题了。
```bash
docker run -d --restart always --name test -v $(pwd)/coolq:/home/user/coolq -v $(pwd)/bot:/home/user/coolqbot/bot -p 9000:9000 -e COOLQ_ACCOUNT=2062765419 -e VNC_PASSWD=12345687 he0119/coolqbot:latest
```

**Comment by he0119** [comment]
并且那个 bot.ini 的配置

```ini
[bot]
# 你的群号
group_id = 438789224
# 是否是 酷Q 专业版
is_coolq_pro = 0
# 管理员 QQ 号
admin = 417557420
# 机器人昵称
nickname = 小誓约 小17
# 图灵机器人的 APIKEY（没有就不用填）
tuling_api_key =
# 腾讯机器人的 APIKEY（没有就不用填）
tencent_ai_app_id =
tencent_ai_app_key =
```

应该是这样的，注释不能跟在后面，我也忘了。🤣

**Comment by RealKiro** [comment]
> 并且那个 bot.ini 的配置
> 
> ```ini
> [bot]
> # 你的群号
> group_id = 438789224
> # 是否是 酷Q 专业版
> is_coolq_pro = 0
> # 管理员 QQ 号
> admin = 417557420
> # 机器人昵称
> nickname = 小誓约 小17
> # 图灵机器人的 APIKEY（没有就不用填）
> tuling_api_key =
> # 腾讯机器人的 APIKEY（没有就不用填）
> tencent_ai_app_id =
> tencent_ai_app_key =
> ```
> 
> 应该是这样的，注释不能跟在后面，我也忘了。🤣

能运行，但是啥都没有
![image](https://user-images.githubusercontent.com/33367701/67443989-badb1700-f639-11e9-9f71-5c8419c28862.png)

![image](https://user-images.githubusercontent.com/33367701/67443954-98e19480-f639-11e9-83b2-60e49f5e2d63.png)

**Comment by he0119** [comment]
你应该可以看看 `docker logs coolqbot` 的输出，大概是没有正常启动？
